### ISSUE TITLE
Mosaicking notebook 

### ISSUE THREAD

**Issue by marcozimmermannpm** [makepath/xarray-spatial#242]
mosaicking-analysis.ipynb

The goal is to create a Notebook that takes Sentinel 2 images for a region over over different times and generates a single, cloud-free scene over that area.

Internal release: 04/06
External release: 04/13

Descriptions from their SOW:

Creating a mosaic from a single multitemporal dataset
"A user is working to apply a machine learning model against Sentinel 2 imagery over a specific area. The user queries a STAC API for sentinel imagery covering that area over a specific time period. This results in many overlapping scenes. The user then uses the library to mosaic the raster data of the scenes into a single mosaiced tile set of the same CRS and resolution, using the median operation to remove clouds. This dataset can be immediately processed by the machine learning model, or written out to a set of COGs for future use."

"For an example, an open source demo notebook that reads all of Sentinel 2 images from our STAC API over 2020 and a country, coregisters all of the images, uses a median operation to merge into a single layer, and save off that layer into Azure blob storage as COGs. This can be one or a series of notebooks that encapsulates and demonstrates all the functionality of this project, and can be used by the AI for Earth team as examples shown in demo situations as well as Planetary Computer documentation (along with general open source documentation for the project itself)."
"For example, taking a median of a raster dataset that has many images over the same area is a technique used to remove clouds and produce a single, cloud-free scene over that area."

Steps:
- [x] Get access to STAC API
- [x] Get Sentinel 2 images over 2020 for the Gulf Coast
- [x] Coregister all the images
- [x] Use median operation to merge into a cloud-free single layer
- [x] Save off that layer into Azure blob storage as COGs

**Comment by giancastro** [comment]
@marcozimmermannpm, can we close this issue?
